### ISSUE TITLE
Dockerizing bleve-wiki-indexer

### ISSUE THREAD

**Issue by lgs** [blevesearch/bleve-wiki-indexer#3]
I just released a  Docker build for [Search the bleve wiki app](http://wikisearch.blevesearch.com/search/).

Here it is the [Docker Hub Public Image](https://registry.hub.docker.com/u/lgsd/docker-bleve-wiki-indexer/) and here the code on [github](https://github.com/lgs/docker-bleve-wiki-indexer).

To have your Docker - containerized - search engine - UP & Running (will take arount 5 mins) do like this:

<pre>
    $ docker run -i -p 8099:8099 -t lgsd/docker-bleve-wiki-indexer bash
    root@52fe5e02d8f9:/# cd $GOPATH/src/github.com/blevesearch/bleve-wiki-indexer
    root@52fe5e02d8f9:/gopath/src/github.com/blevesearch/bleve-wiki-indexer# bleve-wiki-indexer -dir /data/bleve.wiki
    2014/09/07 12:27:17 Creating new index...
    2014/09/07 12:27:18 watching '/data/bleve.wiki' for changes...
    2014/09/07 12:27:18 updated: /data/bleve.wiki/ANSI Result Match Highlighter.md
    2014/09/07 12:27:18 checking commit 1a1083b7093e79890dc480d2b9dad0112a43ffbd
    2014/09/07 12:27:18 checking commit d781519f66ca8894b1a303bd3db3196f95ae04e4
    ...
    2014/09/07 12:27:23 gravatar hash is: 16cdfb0c4af5297e261cb36e30fa5c20
    2014/09/07 12:27:23 Listening on :8099
</pre>

open your browser at  `http://localhost:8099/`, or do `curl` to check it works:

<pre>
    $ curl localhost:8099
    Found
</pre>

**Comment by mschoch** [comment]
We are archiving this project now, as it has not been maintained for quite some time.
